### PR TITLE
Use SD templates

### PR DESCRIPTION
**Pull request by leamas**
Please don't even think about merging this, it is far from ready and might not ever become so. 

That said, some bullets of this approach:
  - Builds on all platforms, also Android.
  - Offers full support without external dependencies for rtldsr on Linux and Macos.
  -  Windows power users can recompile the plugin with rtlsrd support, but this requires installing the libusb driver.
  - Despite some rather complicated dependencies, the code in [Plugin.cmake](https://github.com/rgleason/weatherfax_pi/blob/743a7d80e9adddb08177401824307414606b5eab/Plugin.cmake) which defines the plugin is reasonably simple, basically just a list of dependencies.
  -  All library dependencies are generic, they could for example be dropped as-is into main OpenCPN.
  - The SD templates have basically worked as-is. One bug  https://github.com/Rasbats/shipdriver_pi/issues/448 is filed and fixed, but not yet released.
  - libaudiofile is recognized as the external library it is. Actually, both Linux and Homebrew have this package available and these could be used.
  - The pesky pluginmanager.h header is removed.

### CODE REVIEW

**Comment by rgleason** [comment]
Maybe after things get fixed, I should checkout a new branch master-tp and then merge to try it.
Maybe we should have two versions of weatherfax, weatherfax and weatherfax_rtlsdr.

**Comment by leamas** [comment]
Let's wait for Jon's work with the FE template first. Until then I have anyway work with upstreaming  and reviewing patches, initial testing, etc. Most of these things are not really about the template, it's what comes up when I finally got a complete build chain working.

**Comment by leamas** [comment]
I attach a patch  did to make it build on Android. The issue is basically that the .cpp file refers to 
OnLeftDown and OnLeftRight which is not defined in the header (for Android). I have for now removed the references, but to be honest I have no idea what this is all about. Should the header be fixed instead?

@bdbcat : Do you have some time to review?

[0001-Weatherfax.cpp-Temporary-nasty-Android-fix-to-avoid-.patch.gz](https://github.com/rgleason/weatherfax_pi/files/8785855/0001-Weatherfax.cpp-Temporary-nasty-Android-fix-to-avoid-.patch.gz)

**Comment by leamas** [comment]
Filed upstream patch: https://github.com/seandepagnier/weatherfax_pi/pull/152

**Comment by bdbcat** [comment]
@leamas:
I am not in a position to merge and test build now.
But, in my fork of Ricks repo, I see:
```

#ifdef __OCPN__ANDROID__
    void OnEvtPanGesture( wxQT_PanGestureEvent &event);
#endif    
    void OnLeftDown( wxMouseEvent& event );
    void OnLeftUp( wxMouseEvent& event );

```
Am I looking in the wrong place?

**Comment by leamas** [comment]
No need to merge and test right now. We still don't know if this will land via SD or FE, Jon thinks he can fix the FE template given some time. Of course he should get that time. But, we will eventually run into this anyway.

Yes, it's the right place. Ity basically means that only `OnEvtPanGesture`is defined on Android. OTOH, as you can see in the patch the cpp file also uses OnLeftUp and OnLeftDown, which then are undefined on Android. 

In the patch I just nuked the cpp references to the missing events. But is the correct way to define the in the header for Android instead? I have no idea. Have you?

**Comment by bdbcat** [comment]
"Yes, it's the right place. It basically means that only OnEvtPanGestureis defined on Android. "
Wow that is certainly not how I would read this:
```
#ifdef __OCPN__ANDROID__
    void OnEvtPanGesture( wxQT_PanGestureEvent &event);
#endif    
    void OnLeftDown( wxMouseEvent& event );
    void OnLeftUp( wxMouseEvent& event );

```
I read this:  "OnLeftDown is defined for all builds.  OTOH, OnEvtPanGesture is defined only for Android"
???

**Comment by leamas** [comment]
>  I read this: "OnLeftDown is defined for all builds. OTOH, OnEvtPanGesture is defined only for Android"

"blushes" I'm an idiot, without any doubts whatsoever. Sorry. Can we just forget this part? Please?

Still, with the commented lines uncommented we have:
```
src/WeatherFax.cpp:243:76: error: no member named 'OnLeftUp' in 'WeatherFaxBase'
```
I'll dig some more into this... BBL

**Comment by leamas** [comment]
Solved by (on top of previous patch). Basically WeaherFaxBase -> WeatherFax, looks like a typo. 
```
index 6e39a86f..c63e2387 100644
--- a/src/WeatherFax.cpp
+++ b/src/WeatherFax.cpp
@@ -238,9 +238,8 @@ WeatherFax::WeatherFax( weatherfax_pi &_weatherfax_pi, wxWindow* parent)
     m_lFaxes->GetHandle()->grabGesture(Qt::PanGesture);
     m_lFaxes->Connect( wxEVT_QT_PANGESTURE,
                        (wxObjectEventFunction) (wxEventFunction) &WeatherFax::OnEvtPanGesture, NULL, this );
-// FIXME: Inconsistent w r t  WeatherFax.h, but which is right?
-//    m_lFaxes->Connect( wxEVT_LEFT_DOWN, wxMouseEventHandler( WeatherFaxBase::OnLeftDown ), NULL, this );
-//    m_lFaxes->Connect( wxEVT_LEFT_UP, wxMouseEventHandler( WeatherFaxBase::OnLeftUp ), NULL, this );
+    m_lFaxes->Connect( wxEVT_LEFT_DOWN, wxMouseEventHandler( WeatherFax::OnLeftDown ), NULL, this );
+    m_lFaxes->Connect( wxEVT_LEFT_UP, wxMouseEventHandler( WeatherFax::OnLeftUp ), NULL, this );
     m_tDownTimer.Connect(wxEVT_TIMER, wxTimerEventHandler
                          ( WeatherFax::OnDownTimer ), NULL, this);
 #endif

```
@bdbcat: Thanks for listening...

**Comment by rgleason** [comment]
Alex, thank you. I've made a master-sd branch and merged your work into that.
https://github.com/rgleason/weatherfax_pi/tree/master-sd
It appears that all OS are building.
Also made a similar branch for master-tp

**Comment by leamas** [comment]
It should be ok as long as you keep in a separate branch for test purposes. However, the first line in the description says:

> Please don't even think about merging this, it is far from ready and might not ever become so.

This is still true. The reason I did the PR was mostly to provide an example for Jon. There is still a lot of cleaning up needed before it is prime time for this variant.

But as long as you keep it in master-sd all is fine. I will make additional PRs based on that branch, and since you seem interested I will try to eventually finish this work. However, this will take some time, these are busy days.

**Comment by rgleason** [comment]
Yes, it seemed to compile nicely. I am going to try the Windows version, and try to keep the xml files up to data.

**Pull request closed without merging**
