### PR TITLE
Correct MacOS build

### PR DESCRIPTION
**Pull request by bdbcat**

### CODE REVIEW

**Comment by rgleason** [comment]
Dave, what does this do to Australian BOM files? Anything?

**Comment by rgleason** [comment]
Thanks Dave, I was looking for that and got involve with vdr.  Merged.

**Comment by rgleason** [comment]
Dave, I am going to push this to plugins unless you say not to.
I checked opencpn-libs and our repos have the same number.
Is there anything else I should do?
Are the AUS BOM simply not going to work until the changes to opencpn-libs occurs?
I am not quite sure about how this works.

**Comment by bdbcat** [comment]
Please hold on for a couple of hours.  I will import from Cloudsmith and verify on Mac.
If the solution holds, then everything, including AUS BOM, will work OK.

**Comment by rgleason** [comment]
Ok, 
Weatherfax v1.10.6  (Pick one of the most recent which includes your Correct MacOS build 
https://cloudsmith.io/~opencpn/repos/weatherfax-beta/packages/?q=weatherfax+1.10.6+darwin+tarball

OR
Weatherfax  v1.10.7  - the other version of MacOs is still building but it will appear here
https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/?q=tarball+1.10.7.0+darwin

**Comment by rgleason** [comment]
Now both MacOS versions are available for weatherfax 1.10.7  which is the one I am going to push.
https://cloudsmith.io/~opencpn/repos/weatherfax-prod/packages/?q=1.10.7+tarball+darwin

**Comment by bdbcat** [comment]
1.10.7 is fine, works on MacOS as expected.  AUS BOM seems OK as well.
Ready to publish.

**Comment by rgleason** [comment]
Great. Thank you for all your help. Will publish

**Pull request merged**
