### PR TITLE
Update UK MET Surface Anlys chart correction factor

### PR DESCRIPTION
**Pull request by ThomTrab**
I noticed that the UK MET Surface Anlys is not the same as the others UK MET charts. I create a specific area for it and the corresponding correction factor.

Tested. Work on my side.

### CODE REVIEW

**Comment by rgleason** [comment]
@ThomTrab

Excellent! This is a first time for a Pull Request changing the weatherfax data files.  I love it. This is the best way to do this!  Thank you.  I will look at it more closely today or tomorrow and merge.

**Comment by ThomTrab** [comment]
I'm glad you like it :smile:. To be honest with you, that's my first PR. :wink:. Code revision and GitHub are quite new to me and the learning curve is quite steep.

**Comment by ThomTrab** [comment]
Maybe I shouldn't do it this way, but I didn't know how to do it differently. :wink: 
I continued to add new data for the plugin. I added LaMMA (Italian Weather Forecast Orgnaization). They provide very useful information for sailing in Med.
To be able to match filename and forecast value, I added two new tag in the XML `Offset` and `Step`. These allow linear transformation between `index` and forecast value.

**Comment by rgleason** [comment]
Thank you ThomTrab.  Excellent!

I will try to update and distribute these changes soon.

**Pull request merged**
