### PR TITLE
Tidy up UI menu

### PR DESCRIPTION
**Pull request by ThomTrab**
As an exercises for my self, to get around wxWidgets and OpenCPN plugin, and hopefully for the OpenCPN community, I did some tidying on all menu of the plugin. I don't think these are major changes but, IMO, they improve the look and feel of the plugin.

In the mean time, I broke the File>Preference menu, with is a real mess right now. I have no clue why does this happen. Any help will be much appreciated.

### CODE REVIEW

**Comment by ThomTrab** [comment]
> In the mean time, I broke the File>Preference menu, with is a real mess right now. I have no clue why does this happen. Any help will be much appreciated.
Latest commit fix it

**Comment by rgleason** [comment]
Changing some of this interface is a bit ticklish. I think, I've had to use the most recent wxFormBuilder to modify, but I've not done it for several years!  Perhaps it should be updated, but it can be difficult. You are welcome to try, and we can test the results on various OS. I will make a new branch that you can push to if you'd like. I will update that new branch front-end to be current and you can then push your changes to that branch.

**Comment by rgleason** [comment]
Files will be deployed to Cloudsmith.

**Comment by rgleason** [comment]
@ThomTrab 
I'm in the process of updating weatherfax in the "master-update"  to v1.9.14.3
branch. https://github.com/rgleason/weatherfax_pi/tree/master-update
I've updated the Frontend to v1.0167 from Jon Gough's testplugin_pi  and it is working in windows now.
I have pushed this up to github and it will build the environments in circleci and the successes will deploy to cloudsmith  opencpn  weatherfax-alpha  https://cloudsmith.io/~opencpn/repos/weatherfax-alpha/packages/ 
because it is not the master branch and I did not "tag" the push.  See this "1.9.14.3" search in that repository
https://cloudsmith.io/~opencpn/repos/weatherfax-alpha/packages/?q=1.9.14.3

I intend to close "Tidy up UI Menu" so you can use the most current wxFormBuilder and perhaps make the changes to the UI successfully and then Push the changes to the master-update branch.

You can make a PR to the Master-Uptate branch, by selecting Pull Request from your online repository.
https://github.com/rgleason/weatherfax_pi/tree/master-update

Additionally, I notice that the addition of LMMA low and LMMA high  needs to have the corresponding coordinatedatasets.xml records completed with image wizard so that everyone using the those faxes does not need to use the image wizard to overlay on the charts successfully..

If you can get that coord data included as a separate PR that would be good.

Thanks very much.

**Comment by ThomTrab** [comment]
> I intend to close "Tidy up UI Menu" so you can use the most current wxFormBuilder and perhaps make the changes to the UI successfully and then Push the changes to the master-update branch.

I thought to have the lastest wxFormBuilder, because according to their GitHub 3.9.0 is the latest release. I will make it from source. I will then make a PR to master-update.

> Additionally, I notice that the addition of LMMA low and LMMA high needs to have the corresponding coordinatedatasets.xml records completed with image wizard so that everyone using the those faxes does not need to use the image wizard to overlay on the charts successfully..

Your comment scare me :fearful: , as I though to have lost my work in the winding of Github. I double checked, `coordinatedatasets.xml` including the LAMMA modification is already part of the PR #51 :relieved: . Addition are located at the end of the file. So everyone should enjoy the new additions

**Pull request closed without merging**
