### PR TITLE
Update appveyor.yml to use wxWidgets 3.0.2

### PR DESCRIPTION
**Pull request by jongough**

### CODE REVIEW

**Comment by rgleason** [comment]
Jon, why are you using 3.0  it should be 3.1.2 wxwidgets..
Appveyor line
```
# Download and unzip wxwidgets
  - ps: Start-FileDownload http://opencpn.navnux.org/build_deps/wxWidgets-3.1.2.7z
  - cmd: 7z x wxWidgets-3.1.2.7z -o%WXWIN% > null
```
Mayber there is not a 3.0.2 version to download?

Are you testing something?

**Comment by rgleason** [comment]
Now Appveyor restarted and used the right version 3.1.2,  how does that happen?
I tried to rebuild it twice after failures when it tried to download wxWigets 3.0.2 ?
Then it re built by itself.

**Comment by jongough** [comment]
I got a serve from Alec, I think, about using 3.1.2 and told I should be using 3.0.2 when I started doing this work on the build environments. I thought OCPN 5+ was wxWidgets 3.1.2, but.....

The effective change I made was to add the correct repository for appveyor. I had handled travis and circleci but used a default setting for appveyor which did not take account of the branch that was being built. Hopefully that part will now work correctly.

**Comment by rgleason** [comment]
Thanks, thats better, but appveyor still having trouble.  Something is missing still.

**Pull request merged**
